name: sfr3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pip
  - pip:
      - --index-url https://pypi.org/simple
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - scipy==1.17.1
      - tensorboard==2.20.0
      - torch==2.2.2
      - torchvision==0.17.2
      - pytorch-lightning==1.9.5
      - lightning-bolts==0.7.0
      - matplotlib==3.10.8
      - numpy==1.26.4
      - pyroomacoustics==0.9.0
      - complexPyTorch==0.4
      - scikit-learn==1.8.0
      - scikit-image==0.26.0
      - tqdm==4.67.3